export const DEMO_NOTES = [
  {
    id: 1,
    title: "Calculus — Integration by Parts",
    body: "Integration by parts: ∫u dv = uv − ∫v du\n\nLIATE rule for choosing u:\nLogarithms, Inverse trig, Algebraic, Trig, Exponential\n\nExample: ∫x·eˣ dx\nu = x, dv = eˣ dx\nResult: x·eˣ − eˣ + C",
    module: "GCE 'A' Levels",
    subject: "H2 Math",
    documentType: "Notes/Practices",
    year: "2024",
    uploadedBy: "me",
    tags: ["Math"],
    pinned: true,
    created: "2024-11-10",
    isPdf: false,
    pdfArrayBuffer: null,
  },
  {
    id: 2,
    title: "Newton's Laws of Motion",
    body: "1st Law (Inertia): An object at rest stays at rest unless acted upon by a net force.\n\n2nd Law: F = ma\n\n3rd Law: Every action has an equal and opposite reaction.",
    module: "GCE 'A' Levels",
    subject: "H2 Physics",
    documentType: "Lecture Notes",
    year: "2024",
    uploadedBy: "me",
    tags: ["Physics"],
    pinned: false,
    created: "2024-11-08",
    isPdf: false,
    pdfArrayBuffer: null,
  },
  {
    id: 3,
    title: "Binary Search Trees",
    body: "BST property: left subtree < node < right subtree.\n\nTime complexity:\n• Search: O(log n) avg\n• Insert: O(log n) avg\n• Delete: O(log n) avg\n\nInorder traversal → sorted sequence.",
    module: "University",
    subject: "Data Structures",
    documentType: "Notes/Practices",
    year: "2024",
    uploadedBy: "me",
    tags: ["CS"],
    pinned: true,
    created: "2024-11-05",
    isPdf: false,
    pdfArrayBuffer: null,
  },
  {
    id: 4,
    title: "Big-O Cheatsheet",
    body: "O(1)       — Constant\nO(log n)   — Binary search\nO(n)       — Linear scan\nO(n log n) — Mergesort\nO(n²)      — Nested loops\nO(2ⁿ)      — Recursion",
    module: "University",
    subject: "Algorithms",
    documentType: "Notes/Practices",
    year: "2024",
    uploadedBy: "me",
    tags: ["CS"],
    pinned: false,
    created: "2024-10-28",
    isPdf: false,
    pdfArrayBuffer: null,
  },
  {
    id: 5,
    title: "Thermodynamics Laws",
    body: "0th Law: Thermal equilibrium is transitive.\n1st Law: ΔU = Q − W (energy conservation)\n2nd Law: Entropy of an isolated system always increases.\n3rd Law: S → 0 as T → 0 K",
    module: "GCE 'A' Levels",
    subject: "H2 Chemistry",
    documentType: "Lecture Notes",
    year: "2024",
    uploadedBy: "me",
    tags: ["Physics", "Chemistry"],
    pinned: false,
    created: "2024-10-20",
    isPdf: false,
    pdfArrayBuffer: null,
  },
];
